# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApprunDedicatedProvisioner < Formula
  desc "CLI tool for managing Sakura Cloud AppRun Dedicated application provisioning"
  homepage "https://github.com/tokuhirom/apprun-dedicated-provisioner"
  version "0.0.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.0.28/apprun-dedicated-provisioner_0.0.28_darwin_amd64.tar.gz"
      sha256 "2e499e8d18d35128d47f5c881ac0baf717ced5a3cdc6825f324b709886deee4d"

      def install
        bin.install "apprun-dedicated-provisioner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.0.28/apprun-dedicated-provisioner_0.0.28_darwin_arm64.tar.gz"
      sha256 "80436cd75919dc7775269f36de4fc0b04014310ceb6442516c8b7f088d4cab59"

      def install
        bin.install "apprun-dedicated-provisioner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.0.28/apprun-dedicated-provisioner_0.0.28_linux_amd64.tar.gz"
      sha256 "d69bdd27e33e1da88453093a002f8011b2b23490a8bd3914113a05af4dddf849"
      def install
        bin.install "apprun-dedicated-provisioner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.0.28/apprun-dedicated-provisioner_0.0.28_linux_arm64.tar.gz"
      sha256 "b2e3a6ab5e9f041cbb8ffdc8183504fa56a3e60f1bfd8ecab57da5b7645b03d7"
      def install
        bin.install "apprun-dedicated-provisioner"
      end
    end
  end

  test do
    system "#{bin}/apprun-dedicated-provisioner", "--version"
  end
end
