# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApprunDedicatedApplicationProvisioner < Formula
  desc "CLI tool for managing Sakura Cloud AppRun Dedicated application provisioning"
  homepage "https://github.com/tokuhirom/apprun-dedicated-application-provisioner"
  version "0.0.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.24/apprun-dedicated-application-provisioner_0.0.24_darwin_amd64.tar.gz"
      sha256 "f9563b8c234224cf81990ebcff3d00e17ad8af360a75dea2d71b39c1a4fe6ec5"

      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.24/apprun-dedicated-application-provisioner_0.0.24_darwin_arm64.tar.gz"
      sha256 "9a3fcaad0a836e26b758e4526e7af672b4ee62f3bdeadfd58122e8991f9f8bd1"

      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.24/apprun-dedicated-application-provisioner_0.0.24_linux_amd64.tar.gz"
      sha256 "a009e5c66e75d03b9932ee39cce667b8a0e5ea6de733c0e30c5a002c10584741"
      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.24/apprun-dedicated-application-provisioner_0.0.24_linux_arm64.tar.gz"
      sha256 "6fda946f0f6b52b7ce054ae0ff1dc332d8f1149ddc0686b9a9bdeb57817414be"
      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
  end

  test do
    system "#{bin}/apprun-dedicated-application-provisioner", "--version"
  end
end
