# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApprunDedicatedApplicationProvisioner < Formula
  desc "CLI tool for managing Sakura Cloud AppRun Dedicated application provisioning"
  homepage "https://github.com/tokuhirom/apprun-dedicated-application-provisioner"
  version "0.0.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.25/apprun-dedicated-application-provisioner_0.0.25_darwin_amd64.tar.gz"
      sha256 "3c85b1b72b3c6cfe8f800ff67adfd3295f290afc7b2fed9194b2fff5cc7a99d6"

      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.25/apprun-dedicated-application-provisioner_0.0.25_darwin_arm64.tar.gz"
      sha256 "66c157886b31b3fdcbd01fdd9c063671b8c1854d0332b9d840014393734f227f"

      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.25/apprun-dedicated-application-provisioner_0.0.25_linux_amd64.tar.gz"
      sha256 "a3e9abcfb380d5678c048b6e4ab3b9b19e5f0824a8a27ccfd18747ac5efd7934"
      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/apprun-dedicated-application-provisioner/releases/download/v0.0.25/apprun-dedicated-application-provisioner_0.0.25_linux_arm64.tar.gz"
      sha256 "8966700732667298da5eed49f15d51c557346dc7c06125fc2ccdfdec2d667d71"
      def install
        bin.install "apprun-dedicated-application-provisioner"
      end
    end
  end

  test do
    system "#{bin}/apprun-dedicated-application-provisioner", "--version"
  end
end
