# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcv < Formula
  desc "Docker Compose Viewer - A TUI tool for monitoring Docker Compose applications"
  homepage "https://github.com/tokuhirom/dcv"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.1.0/dcv_darwin_amd64.tar.gz"
      sha256 "8c783573fedc495129348182b0ff631499da8380ee7dcb936d4b16fdd3ac5b25"

      def install
        bin.install "dcv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.1.0/dcv_darwin_arm64.tar.gz"
      sha256 "3bd26d152eb861c98cf7813746f960c9605cdea951296f7153cc60a895327b18"

      def install
        bin.install "dcv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.1.0/dcv_linux_amd64.tar.gz"
      sha256 "3c8e77fa70034ae01e4e84ed7bce14c5273cd42206ed4920014f6171fb9201fb"
      def install
        bin.install "dcv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.1.0/dcv_linux_arm64.tar.gz"
      sha256 "ac4f8cd763ab4326fb7801358f039a84e34cfbc2b1773c5d2d95508c64a24ffe"
      def install
        bin.install "dcv"
      end
    end
  end

  test do
    system "#{bin}/dcv", "--version"
  end
end
