# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcv < Formula
  desc "Docker Compose Viewer - A TUI tool for monitoring Docker Compose applications"
  homepage "https://github.com/tokuhirom/dcv"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.3.2/dcv_darwin_amd64.tar.gz"
      sha256 "786aaa9738f96548ea2d0d54052965cdd91e4a5b58b3e2b07ade26264be8f4f1"

      def install
        bin.install "dcv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.3.2/dcv_darwin_arm64.tar.gz"
      sha256 "174d708aab4ae41d520e7eb340ae18510f1ba15e4b839c7df6a6a6ed7db54652"

      def install
        bin.install "dcv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.3.2/dcv_linux_amd64.tar.gz"
      sha256 "e0795b6b8d11eb03e8f71b0ba23467e2418f30f5956f426bbfd8643ec80f48bb"
      def install
        bin.install "dcv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/dcv/releases/download/v0.3.2/dcv_linux_arm64.tar.gz"
      sha256 "c4da14cb8442f23cf1feadcc65e27b31fa9199efae866882a8c228d4913519d9"
      def install
        bin.install "dcv"
      end
    end
  end

  test do
    system "#{bin}/dcv", "--version"
  end
end
