# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskeru < Formula
  desc "Taskeru - task management tool"
  homepage "https://github.com/tokuhirom/taskeru"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.2/taskeru_darwin_amd64.tar.gz"
      sha256 "689217d4664d46a4f994cdbcca2474bd7c13e322909a497e9bbdd439b6797711"

      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.2/taskeru_darwin_arm64.tar.gz"
      sha256 "4a8389963b75ed2efead6b4d7cb61672f0cfd9e1f51ee7c6cdd7888f3665283b"

      def install
        bin.install "taskeru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.2/taskeru_linux_amd64.tar.gz"
      sha256 "6f7314c476e2e47b44499ba89f7f210a749e76a7384a398f2f317e2508bee87c"
      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.2/taskeru_linux_arm64.tar.gz"
      sha256 "6b6fd2f4ed700419d3f5de3a030f6f0cdcf8d8aac6367bd58d5c0cbf52d16e68"
      def install
        bin.install "taskeru"
      end
    end
  end

  test do
    system "#{bin}/taskeru", "--version"
  end
end
