# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskeru < Formula
  desc "Taskeru - task management tool"
  homepage "https://github.com/tokuhirom/taskeru"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.4/taskeru_darwin_amd64.tar.gz"
      sha256 "a85db7d1b8073209b5a28bd971c906b245e603080acc65c059c680ab6d8dfb62"

      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.4/taskeru_darwin_arm64.tar.gz"
      sha256 "26f42b387ea72c81ec43ccde06195f49a34081b7991c97733fcf95af863cb274"

      def install
        bin.install "taskeru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.4/taskeru_linux_amd64.tar.gz"
      sha256 "7aca8bb8d7a1243bf81e36a755151e739186f0279bd20692fa2d4b3413d5371b"
      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.4/taskeru_linux_arm64.tar.gz"
      sha256 "82ac53779061e704e3b6740179311779520a6a91be1eea92a66abb10d7a6734c"
      def install
        bin.install "taskeru"
      end
    end
  end

  test do
    system "#{bin}/taskeru", "--version"
  end
end
