# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskeru < Formula
  desc "Taskeru - task management tool"
  homepage "https://github.com/tokuhirom/taskeru"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.3/taskeru_darwin_amd64.tar.gz"
      sha256 "440ea421987c74d931e26330a0b7f4c18a9f0f6d7f6e906023c4d5d87de4b4eb"

      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.3/taskeru_darwin_arm64.tar.gz"
      sha256 "519ef49d135de6a602f309aaedfe871131fa865e928c09cd571e6cf80154a40d"

      def install
        bin.install "taskeru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.3/taskeru_linux_amd64.tar.gz"
      sha256 "415532f6bc9a05834bfd6fefc3d63c5aaab708164aef40ff93cfd76a449d4dbd"
      def install
        bin.install "taskeru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/tokuhirom/taskeru/releases/download/v0.0.3/taskeru_linux_arm64.tar.gz"
      sha256 "21e1856a29a82a72efe48fe3ad8af5cfad256ed90291354c88a537ac5a878d55"
      def install
        bin.install "taskeru"
      end
    end
  end

  test do
    system "#{bin}/taskeru", "--version"
  end
end
